"""
Django settings for webcaf project.

Generated by 'django-admin startproject' using Django 5.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import base64
import os
from pathlib import Path
from urllib.parse import urlsplit

from csp.constants import NONCE, SELF
from django.core.exceptions import ImproperlyConfigured
from environ import Env
from govuk_onelogin_django.types import AuthenticationLevel, IdentityConfidenceLevel

env = Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

Env.read_env(os.path.join(BASE_DIR, ".env"))

DEBUG = env.bool("DEBUG")
if DEBUG:
    # Use dotenv for debug environments
    from dotenv import load_dotenv

    load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = env.str("SECRET_KEY", default="not_set")  # type: ignore

if SECRET_KEY == "not_set" and not DEBUG:  # pragma: allowlist secret
    raise Exception("SECRET_KEY must be set in production")

APPEND_SLASH = True
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])
ENVIRONMENT = env.str("ENVIRONMENT", default=None)

X_FRAME_OPTIONS = "SAMEORIGIN"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "govuk_frontend_django",
    "webcaf.webcaf.apps.WebcafConfig",
    "csp",
    "django_otp",
    "django_otp.plugins.otp_email",
    "govuk_onelogin_django",
    "mozilla_django_oidc",
    "simple_history",
    "axes",
]

AUTHENTICATION_BACKENDS = (
    "webcaf.auth.OIDCBackend",
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
)

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "webcaf.middleware.RequestLoggingMiddleware",
    "axes.middleware.AxesMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "webcaf.session.CafSessionTimeoutMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "webcaf.middleware.AssessmentDoesNotExistHandlerMiddleware",
    "webcaf.middleware.AssessmentNotSelectedHandlerMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "webcaf.auth.LoginRequiredMiddleware",
    "webcaf.middleware.LastOrganisationCookieMiddleware",
    "webcaf.middleware.DisableCacheMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "webcaf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "webcaf", "templates"),
            os.path.join(BASE_DIR, "webcaf", "templates", "caf"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "webcaf.context_processors.variable_page_content",
            ],
        },
    },
]

WSGI_APPLICATION = "webcaf.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if "RDS_DB_NAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["RDS_DB_NAME"],
            "USER": os.environ["RDS_USERNAME"],
            "PASSWORD": os.environ["RDS_PASSWORD"],
            "HOST": os.environ["RDS_HOST"],
            "PORT": os.environ["RDS_PORT"],
            "OPTIONS": {
                "connect_timeout": 5,
            },
        }
    }
else:
    DATABASES = {
        "default": env.db_url(default="postgresql:///webcaf"),  # type: ignore
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "webcaf", "static"),
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL = "/assets/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# Django Whitenoise Configuration
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = [".map"]
WHITENOISE_ALLOW_ALL_ORIGINS = False
if not DEBUG:
    WHITENOISE_AUTOREFRESH = False  # Don't auto-reload in production
    WHITENOISE_MAX_AGE = 86400  # 24 hours (in seconds)
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
AWS_STORAGE_BUCKET_NAME = env.str("S3_DATA_BUCKET", "")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRAMEWORK_PATH = os.path.join(BASE_DIR, "..", "frameworks", "cyber-assessment-framework-v3.2.yaml")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "request_context": {
            "()": "webcaf.logging_filters.RequestLogFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] [%(process)d:%(threadName)s] [user=%(user_id)s sess=%(session_id)s] [%(levelname)s] [%(name)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S %z",
        },
    },
    "handlers": {
        "console": {
            "level": ("INFO" if not DEBUG else "DEBUG"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_context"],
        },
    },
    "loggers": {
        "": {
            "level": ("INFO" if not DEBUG else "DEBUG"),
            "handlers": ["console"],
            "propagate": True,
        },
        # Get SQL query logs in development
        "django.db.backends": {
            "handlers": ["console"],
            "level": ("WARN" if not DEBUG else "DEBUG"),
            "propagate": False,
        },
    },
}

SSO_MODE = env.str("SSO_MODE", "one-login").lower()
if SSO_MODE not in {"external", "one-login", "dex", "local", "localhost", "none"}:
    raise ImproperlyConfigured(f"Unsupported SSO_MODE: {SSO_MODE}")

if SSO_MODE == "external":
    OIDC_RP_CLIENT_ID = env.str("OIDC_RP_CLIENT_ID")
    OIDC_RP_CLIENT_SECRET = env.str("OIDC_RP_CLIENT_SECRET")  # pragma: allowlist secret
    OIDC_OP_AUTHORIZATION_ENDPOINT = env.str("OIDC_OP_AUTHORIZATION_ENDPOINT")
    OIDC_OP_TOKEN_ENDPOINT = env.str("OIDC_OP_TOKEN_ENDPOINT")
    OIDC_OP_USER_ENDPOINT = env.str("OIDC_OP_USER_ENDPOINT")
    OIDC_OP_JWKS_ENDPOINT = env.str("OIDC_OP_JWKS_ENDPOINT")
    OIDC_OP_LOGOUT_ENDPOINT = env.str("OIDC_OP_LOGOUT_ENDPOINT")
    OIDC_STORE_ID_TOKEN = True
    OIDC_STORE_ACCESS_TOKEN = True
    LOGOUT_REDIRECT_URL = env.str("LOGOUT_REDIRECT_URL")
    NOTIFY_API_KEY = env.str("NOTIFY_API_KEY", "")
    NOTIFY_OTP_TEMPLATE_ID = env.str("NOTIFY_OTP_TEMPLATE_ID", "")
    # Disable 2FA in dev and test environments, this is needed to enable access for more than
    # 5 users as the Notify service does not allow us to use more than 5 users
    # for the non-live notify service
    ENABLED_2FA = ENVIRONMENT not in ["dev", "test"]
elif SSO_MODE == "one-login":
    AUTHENTICATION_BACKENDS = (
        "webcaf.auth.OneLoginBackend",
        "axes.backends.AxesStandaloneBackend",
        "django.contrib.auth.backends.ModelBackend",
    )
    LOGIN_URL = "one_login:login"
    GOV_UK_ONE_LOGIN_CLIENT_ID = env.str("GOV_UK_ONE_LOGIN_CLIENT_ID")
    GOV_UK_ONE_LOGIN_OPENID_CONFIG_URL = env.str("GOV_UK_ONE_LOGIN_OPENID_CONFIG_URL")
    GOV_UK_ONE_LOGIN_SCOPE = env.str("GOV_UK_ONE_LOGIN_SCOPE", "openid email")
    GOV_UK_ONE_LOGIN_ENVIRONMENT = env.str("GOV_UK_ONE_LOGIN_ENVIRONMENT", "integration")
    GOV_UK_ONE_LOGIN_AUTHENTICATION_LEVEL = AuthenticationLevel.MEDIUM_LEVEL
    GOV_UK_ONE_LOGIN_CONFIDENCE_LEVEL = IdentityConfidenceLevel.NONE
    GOV_UK_ONE_LOGIN_BACK_CHANNEL_ENABLED = False

    configured_client_secret = env.str("GOV_UK_ONE_LOGIN_CLIENT_SECRET", "")
    private_key_path = env.str("GOV_UK_ONE_LOGIN_PRIVATE_KEY_PATH", "")
    if configured_client_secret and private_key_path:
        raise ImproperlyConfigured(
            "Set either GOV_UK_ONE_LOGIN_CLIENT_SECRET or GOV_UK_ONE_LOGIN_PRIVATE_KEY_PATH, not both"
        )
    if private_key_path:
        resolved_private_key_path = Path(private_key_path).expanduser()
        if not resolved_private_key_path.is_file():
            raise ImproperlyConfigured("GOV_UK_ONE_LOGIN_PRIVATE_KEY_PATH does not point to a readable key")
        configured_client_secret = base64.b64encode(resolved_private_key_path.read_bytes()).decode("ascii")
    if not configured_client_secret:
        raise ImproperlyConfigured(
            "GOV_UK_ONE_LOGIN_CLIENT_SECRET or GOV_UK_ONE_LOGIN_PRIVATE_KEY_PATH must be configured"
        )
    GOV_UK_ONE_LOGIN_CLIENT_SECRET = configured_client_secret

    NOTIFY_API_KEY = env.str("NOTIFY_API_KEY", "")
    NOTIFY_OTP_TEMPLATE_ID = env.str("NOTIFY_OTP_TEMPLATE_ID", "")
    ENABLED_2FA = False
else:
    sso_host = "dex" if SSO_MODE == "dex" else "localhost"
    OIDC_RP_CLIENT_ID = "my-django-app"
    OIDC_RP_CLIENT_SECRET = "my-django-secret"  # pragma: allowlist secret
    # We need to override the host to docker compose container name
    # When we run behave tests in docker
    OIDC_OP_AUTHORIZATION_ENDPOINT = f"http://{env.str('OVERRIDE_SSO_HOST', 'localhost')}:5556/auth"
    OIDC_OP_TOKEN_ENDPOINT = f"http://{sso_host}:5556/token"
    OIDC_OP_USER_ENDPOINT = f"http://{sso_host}:5556/userinfo"
    OIDC_OP_JWKS_ENDPOINT = f"http://{sso_host}:5556/keys"
    OIDC_STORE_ID_TOKEN = True
    OIDC_STORE_ACCESS_TOKEN = True
    OIDC_OP_LOGOUT_ENDPOINT = f"http://{env.str('OVERRIDE_SSO_HOST', 'localhost')}:5556/auth/logout"
    LOGOUT_REDIRECT_URL = f"http://{env.str('OVERRIDE_APP_HOST', 'localhost')}:8010/"
    # if we enable 2fa locally for testing this ensures we capture the token in the local console
    # rather than attempting to a send gov notify email
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    ENABLED_2FA = False

if SSO_MODE != "one-login":
    LOGIN_URL = "oidc_authentication_init"

# The provider logout redirect follows a submitted local form. Chrome applies
# form-action to that redirect, so allow only the configured provider origin.
provider_config_url = GOV_UK_ONE_LOGIN_OPENID_CONFIG_URL if SSO_MODE == "one-login" else OIDC_OP_LOGOUT_ENDPOINT
provider_config = urlsplit(provider_config_url)
provider_origin = f"{provider_config.scheme}://{provider_config.netloc}"

# Content Security Policy: only allow images, stylesheets and scripts from the
# same origin as the HTML.
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "connect-src": (
            SELF,
            "https://*.google-analytics.com",
            "https://*.analytics.google.com",
            "https://*.googletagmanager.com",
        ),
        "form-action": (SELF, provider_origin),
        "frame-ancestors": (SELF,),
        "frame-src": (SELF, NONCE, "https://www.googletagmanager.com"),
        "img-src": (SELF, NONCE, "data:"),
        "script-src": (
            SELF,
            NONCE,
            "sha256-nBhTljJHpMrd9MOPzdAm2s1BkTJWObIEdVxg/bet7PE=",  # pragma: allowlist secret
            "https://*.googletagmanager.com",
        ),
        "style-src": (
            SELF,
            NONCE,
        ),
    }
}

# If we want to test CSP breaches we need to set a fake reporting URL, so the tests
# check if it's been called.
if "TEST_CSP" in os.environ:
    CSP_REPORT_URI = "/csp-report"  # The URI doesn't exist but is intercepted by the test suite

# Confirmation email template ID
# System will not send a confirmation email if this is not set
NOTIFY_CONFIRMATION_TEMPLATE_ID = env.str("NOTIFY_CONFIRMATION_TEMPLATE_ID", "")
NOTIFY_ASSESSMENT_READY_TEMPLATE_ID = env.str("NOTIFY_ASSESSOR_EMAIL_TEMPLATE_ID", "")
# Email
NOTIFY_REVIEW_FINALISED_TEMPLATE_ID = env.str("NOTIFY_REVIEW_FINALISED_TEMPLATE_ID", "")
NOTIFY_TIP_APPROVED_TEMPLATE_ID = env.str("NOTIFY_TIP_APPROVED_TEMPLATE_ID", "")
NOTIFY_TIP_REJECTED_TEMPLATE_ID = env.str("NOTIFY_TIP_REJECTED_TEMPLATE_ID", "")
NOTIFY_TIP_SUBMITTED_TEMPLATE_ID = env.str("NOTIFY_TIP_SUBMITTED_TEMPLATE_ID", "")

OIDC_RP_SCOPES = env.str("OIDC_RP_SCOPES", "openid email profile")
OIDC_RP_SIGN_ALGO = env.str("OIDC_RP_SIGN_ALGO", "RS256")
if DEBUG:
    OIDC_VERIFY_SSL = False

ALLOW_LOGOUT_GET_METHOD = True
LOGIN_REDIRECT_URL = "/my-account/"
LOGIN_REDIRECT_URL_FAILURE = "/authentication-error/"

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_TRUSTED_ORIGINS = [f"https://{os.environ.get('DOMAIN_NAME', 'localhost')}"]
    # CSRF_FAILURE_VIEW = "webcaf.request.views.csrf_failure_view"
    SESSION_COOKIE_SECURE = True

# Admin site login attempt limit

AXES_LOCKOUT_PARAMETERS = ["username"]

# Optional: lockout time in hours
AXES_COOLOFF_TIME = 1
AXES_FAILURE_LIMIT = 5
AXES_LOCKOUT_TEMPLATE = "429.html"

SENTRY_DSN = env.str("SENTRY_DSN", default=None)
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.types import SamplingContext

    def scrub_headers(event, hint):
        request = event.get("request", {})
        headers = request.get("headers", {})

        # remove or redact your header(s)
        if "X-Cf-Key" in headers:
            del headers["X-Cf-Key"]

        # write headers back
        request["headers"] = headers
        event["request"] = request

        return event

    def traces_sampler(sampling_context: SamplingContext) -> float:
        """
        Sets up custom sampling rate for specific scenarios.

        :param: sampling_context: Internal interface from Sentry for sampling callback
        :return: sampling rate
        """
        # Disable health Check trace sampling
        if (
            sampling_context["transaction_context"]["name"] == "generic WSGI request"
            and sampling_context["wsgi_environ"]["HTTP_USER_AGENT"] == "ELB-HealthChecker/2.0"
        ):
            return 0.0
        else:
            # Any other trace sampling rate - prod: 100%, non-prod: 20%
            return 0.2 if ENVIRONMENT != "prod" else 1.0

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        traces_sampler=traces_sampler,
        before_send=scrub_headers,
        before_send_transaction=scrub_headers,
    )

# sets session timeout at 90 minutes
USER_IDLE_TIMEOUT = 90 * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Only send emails for staging and prod environments
SEND_ASSESSMENT_COMPLETION_EMAILS = ENVIRONMENT in ["staging", "prod"]

# CAF Router Version
WEBCAF_VERSION = "caf40"
