[behave]
# other Behave settings
show_skipped = true

[behave.userdata]
base_url = http://localhost:8010
; These identifiers are used to remove scenario data between tests in the disposable test database.
user_emails = alice@example.gov.uk, admin@example.gov.uk, other@example.gov.uk, cyber_advisor@example.gov.uk, test_assessor@example.com, the.tester@example.gov.uk
organisation_names = Ministry of Agriculture, Ministry of Forestry, Ministry of Cake
