# Generated by Django 5.1.15 on 2026-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcaf", "0034_allowedemaildomain_historicalallowedemaildomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="framework",
            field=models.CharField(
                choices=[("caf32", "Cyber Assessment Framework v3.2"), ("caf40", "Cyber Assessment Framework v4.0")],
                default="caf40",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="framework",
            field=models.CharField(
                choices=[("caf32", "Cyber Assessment Framework v3.2"), ("caf40", "Cyber Assessment Framework v4.0")],
                default="caf40",
                max_length=255,
            ),
        ),
    ]
