Feature: Cyber advisor can maintain systems


  Background:
    Given Organisation "Ministry of Agriculture" of type "ministerial-department" exists with systems "System 1, System 2, System 3"
#    Database does not store the passwords
    And the user "cyber_advisor@example.gov.uk" exists
    And User "cyber_advisor@example.gov.uk" has the profile "Cyber advisor" assigned in "Ministry of Agriculture"
    And the application is running
    And cookies have been "accepted"
    And the user logs in with username  "cyber_advisor@example.gov.uk" and password "password"
    And there is no system with name "My system" for organisation "Ministry of Agriculture"


  Scenario: Cyber advisor can see option to create systems
    Given Think time 1 seconds
    Then they should see page title "Cyber advisor - My account - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And current organisation is set to "Ministry of Agriculture"
    And a button with text "Add a new system"
    And link with text "View systems"
    And link with text "Manage users"
    When click link with text "View systems"
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "System 1"
    And link with text "System 2"
    And link with text "System 3"

  Scenario: Cyber advisor can crete new System
    Given Think time 1 seconds
    Then they should see page title "Cyber advisor - My account - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And current organisation is set to "Ministry of Agriculture"
    And a button with text "Add a new system"
    And link with text "View systems"
    And link with text "Manage users"
    When click link with text "View systems"
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "System 1"
    And link with text "System 2"
    And link with text "System 3"
    And click button with text "Continue"
    And enter text "My system" for id "id_name"
    And select radio with value "supports_other_critical_systems"
    And select radio with value "owned_by_another_government_organisation"
    And select radio with value "hosted_hybrid"
    And select radio with value "assessed_in_2425"
    And select checkbox with value "email_and_communication"
    And click button with text "Save and continue"
    Then they should see page title "Check system details - Complete a WebCAF self-assessment - GOV.UK"
    Then they should see a summary card with header "Ministry of Agriculture" keys "System name,System description,Previous GovAssure self-assessments, System ownership,Hosting and connectivity,Corporate services" and values "My system,It provides core infrastructure essential for other critical systems to function,'Yes, in 2024/25', Another government organisation,Hybrid,Email and communication"
    And click button with text "Save and continue"
#    User should see the new system in the system details page
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "My system"
    And System "does" exist with name "My system" for organisation "Ministry of Agriculture"


  Scenario: Cyber advisor can update a System
    Given Think time 1 seconds
    Then they should see page title "Cyber advisor - My account - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And current organisation is set to "Ministry of Agriculture"
    And a button with text "Add a new system"
    And link with text "View systems"
    And link with text "Manage users"
    When click link with text "View systems"
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "System 1"
    And link with text "System 2"
    And link with text "System 3"
    And click link with text "System 3"
    And select radio with value "supports_other_critical_systems"
    And select radio with value "owned_by_another_government_organisation"
    And select radio with value "hosted_hybrid"
    And select radio with value "assessed_in_2425"
    And select checkbox with value "email_and_communication"
    And click button with text "Save and continue"
    Then they should see page title "Check system details - Complete a WebCAF self-assessment - GOV.UK"
    Then they should see a summary card with header "Ministry of Agriculture" keys "System name,System description,Previous GovAssure self-assessments, System ownership,Hosting and connectivity,Corporate services" and values "System 3,It provides core infrastructure essential for other critical systems to function,'Yes, in 2024/25', Another government organisation,Hybrid,Email and communication"
    And click button with text "Save and continue"
#    User should see the new system in the system details page
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And System "does" exist with name "System 3" for organisation "Ministry of Agriculture"

  Scenario: Cyber advisor can crete new System, review summary card and change
    Given Think time 1 seconds
    Then they should see page title "Cyber advisor - My account - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And current organisation is set to "Ministry of Agriculture"
    And a button with text "Add a new system"
    And link with text "View systems"
    And link with text "Manage users"
    When click link with text "View systems"
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "System 1"
    And link with text "System 2"
    And link with text "System 3"
    And click button with text "Continue"
    And enter text "My system" for id "id_name"
    And select radio with value "supports_other_critical_systems"
    And select radio with value "owned_by_another_government_organisation"
    And select radio with value "hosted_hybrid"
    And select radio with value "assessed_in_2425"
    And select checkbox with value "email_and_communication"
    And click button with text "Save and continue"
    Then they should see page title "Check system details - Complete a WebCAF self-assessment - GOV.UK"
    Then they should see a summary card with header "Ministry of Agriculture" keys "System name,System description,Previous GovAssure self-assessments, System ownership,Hosting and connectivity,Corporate services" and values "My system,It provides core infrastructure essential for other critical systems to function,'Yes, in 2024/25', Another government organisation,Hybrid,Email and communication"
    And click button with text "Change"
    And select radio with value "hosted_on_cloud"
    And click button with text "Save and continue"
    Then they should see page title "Check system details - Complete a WebCAF self-assessment - GOV.UK"
    Then they should see a summary card with header "Ministry of Agriculture" keys "System name,System description,Previous GovAssure self-assessments, System ownership,Hosting and connectivity,Corporate services" and values "My system,It provides core infrastructure essential for other critical systems to function,'Yes, in 2024/25', Another government organisation,Cloud hosted,Email and communication"
    And click button with text "Save and continue"
#    User should see the new system in the system details page
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "My system"
    And System "does" exist with name "My system" for organisation "Ministry of Agriculture"

  Scenario: Cyber advisor can update and then change a System
    Given Think time 1 seconds
    Then they should see page title "Cyber advisor - My account - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And current organisation is set to "Ministry of Agriculture"
    And a button with text "Add a new system"
    And link with text "View systems"
    And link with text "Manage users"
    When click link with text "View systems"
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "System 1"
    And link with text "System 2"
    And link with text "System 3"
    And click link with text "System 3"
    And select radio with value "supports_other_critical_systems"
    And select radio with value "owned_by_another_government_organisation"
    And select radio with value "hosted_hybrid"
    And select radio with value "assessed_in_2425"
    And select checkbox with value "email_and_communication"
    And click button with text "Save and continue"
    Then they should see page title "Check system details - Complete a WebCAF self-assessment - GOV.UK"
    Then they should see a summary card with header "Ministry of Agriculture" keys "System name,System description,Previous GovAssure self-assessments, System ownership,Hosting and connectivity,Corporate services" and values "System 3,It provides core infrastructure essential for other critical systems to function,'Yes, in 2024/25', Another government organisation,Hybrid,Email and communication"
    And click button with text "Change"
    And select radio with value "hosted_on_cloud"
    And click button with text "Save and continue"
    Then they should see page title "Check system details - Complete a WebCAF self-assessment - GOV.UK"
    Then they should see a summary card with header "Ministry of Agriculture" keys "System name,System description,Previous GovAssure self-assessments, System ownership,Hosting and connectivity,Corporate services" and values "System 3,It provides core infrastructure essential for other critical systems to function,'Yes, in 2024/25', Another government organisation,Cloud hosted,Email and communication"
    And click button with text "Save and continue"
#    User should see the new system in the system details page
    Then they should see page title "Manage Systems - cyber_advisor - Complete a WebCAF self-assessment - GOV.UK"
    And link with text "System 3"
    And System "does" exist with name "System 3" for organisation "Ministry of Agriculture"
