Feature: Organisation user filling assessments

  Background:
    Given Organisation "Ministry of Agriculture" of type "ministerial-department" exists with systems "System 1, System 2, System 3"
#    Database does not store the passwords
    And the user "alice@example.gov.uk" exists
    And User "alice@example.gov.uk" has the profile "Organisation user" assigned in "Ministry of Agriculture"
    And the application is running
    And cookies have been "accepted"
    And there is a "enhanced" profile assessment  for "System 1", "Ministry of Agriculture", for the period "current" in "draft" status and data " "
    And the user logs in with username  "alice@example.gov.uk" and password "password"

  Scenario: Organisation user complete assessment process
    Given Think time 1 seconds
    Then they should see page title "Organisation user - My account - alice - Complete a WebCAF self-assessment - GOV.UK"
    And click link with text "View 1 draft self-assessment"
    And page has heading "Your draft self-assessments"
    And click link in table row containing value "System 1" with text "View"
    Then page has heading "Complete a WebCAF self-assessment"
    And get assessment id from url and add to context
    #    Fill objective A
    Then navigate to "Objective A: Managing security risk"
    And Fill outcome "A1.a Board Direction" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A1.b Roles and Responsibilities" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A1.c Decision-making" with "achieved, partially-achieved, not-achieved" with "all,none,all"
    And Fill outcome confirm status "Not achieved" with "This is a test outcome comment"
    And Fill outcome "A2.a Risk Management Process" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A2.b Understanding Threat" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A2.c Assurance" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A3.a Asset Management" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A4.a Supply Chain" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "A4.b Secure Software Development and Support" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    #    Move to the new section
    Then click button with text "Save and continue"
    Then navigate to "Objective B: Protecting against cyber attack"
    And Fill outcome "B1.a Policy, Process and Procedure Development" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B1.b Policy, Process and Procedure Implementation" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B2.a Identity Verification, Authentication and Authorisation" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B2.b Device Management" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B2.c Privileged User Management" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B2.d Identity and Access Management (IdAM)" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B3.a Understanding Data" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B3.b Data in Transit" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B3.c Stored Data" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B3.d Mobile Data" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B3.e Media / Equipment Sanitisation" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B4.a Secure by Design" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B4.b Secure Configuration" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B4.c Secure Management" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B4.d Vulnerability Management" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B5.a Resilience Preparation" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B5.b Design for Resilience" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B5.c Backups" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B6.a Cyber Security Culture" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "B6.b Cyber Security Training" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    #    Next section
    Then click button with text "Save and continue"
    Then navigate to "Objective C: Detecting Cyber Security Events"
    And Fill outcome "C1.a Sources and Tools for Logging and Monitoring" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "C1.b Securing Logs" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "C1.c Generating Alerts" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "C1.d Triage of Security Alerts" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "C1.e Personnel Skills for Monitoring and Detection" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "C1.f Understanding User's and System's Behaviour, and Threat Intelligence" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "C2.a Threat Hunting" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    #    Next section
    Then click button with text "Save and continue"
    Then navigate to "Objective D: Minimising the impact of cyber security incidents"
    And Fill outcome "D1.a Response Plan" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "D1.b Response and Recovery Capability" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "D1.c Testing and Exercising" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "D2.a Post Incident Analysis" with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    And Fill outcome "D2.b Using Incidents to Drive Improvements " with "achieved, partially-achieved, not-achieved" with "all,none,none"
    And Fill outcome confirm status "Achieved" with "This is a test outcome comment"
    Then click button with text "Back to draft self-assessment"
    And confirm the current assessment has expected data "alice_completed_assessment.json"
